### ISSUE TITLE
Kubernetes 发布docker学习

### ISSUE THREAD

**Issue by wmenjoy** [wmenjoy/awesome-knowleges#21]
# 使用kubectl + yaml配置部署docker
## 定义deployment.tpl
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %%work.name%%
  labels:
    app.kubernetes.io/name: %%work.name%%
    app.kubernetes.io/env: %%work.env%%
spec:
  replicas: %%work.replicaCount%%
  selector:
    matchLabels:
      app.kubernetes.io/name: %%work.name%%
      app.kubernetes.io/env: %%work.env%%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: %%work.name%%
        app.kubernetes.io/env: %%work.env%%
    spec:
      containers:
        - name: %%work.name%%
          image: %%work.image.repository%%:%%work.image.version%%
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: %%work.limit.cpu%%
              memory: %%work.limit.memory%%
            requests:
              cpu: %%work.limit.cpu%%
              memory: %%work.limit.memory%%
```
## deployment的生成脚本
``` bash


#!/bin/bash ARGS=`getopt -o n:c:i:v:e:f:l:c:m --long name:,env:,replicaCount:,image:,version:,file:,:templateFile,cpu:,memory:,limitCPU:,limitMemory:,requestCPU:,requestMemory: -n 'mkdeployment.sh' -- "$@"`  if [ $? != 0 ]; then   echo "参数错误 ./mkservice.sh -n $name"   exit 1fi # echo $ARGSeval set -- "$ARGS" while truedo  case "$1" in      -n\|--name)        name=$2        shift 2        ;;      -e\|--env)        env=$2        shift 2        ;;      -f\|--file)        outFile=$2        shift 2        ;;      -l\|--templateFile)        templateFile=$2        shift 2        ;;      -c\|--replicaCount)        replicaCount=$2        shift 2        ;;      -i\|--image)        image=$2        shift 2        ;;      -v\|--version)        version=$2        shift 2        ;;      -c\|--cpu)        cpu=$2        shift 2        ;;      -m\|--memory)        memory=$2        shift 2        ;;      --limitCPU)        limitCPU=$2        shift 2        ;;      --limitMemory)        limitMemory=$2        shift 2        ;;      --requestCPU)        requestCPU=$2        shift 2        ;;      --requestMemory)        requestMemory=$2        shift 2        ;;      --)        shift        break        ;;      *)        echo "error"        exit 1        ;;  esacdone if [  "$#" -gt 0 ]; then  echo "使用了多余的参数，请检查"  for arg in $@  do    echo "processing $arg"  done  exit 1fi  [ -z "$name" ] && echo "name 不能为空" && exit 1;[ -z "$image" ] && echo "image 参数不能为空" && exit 1;env=${env:-test}replicaCount=${replicaCount:-1}version=${version:-latest} [ -z "$cpu" ] && cpu=100m[ -z "$memory" ] && memory=256Mi [ -z "$requestCPU" -a ! -z "$cpu" ] && requestCPU=$cpu[ -z "$requestMemory" -a ! -z "$memory" ] && requestMemory=$memory [ -z "$limitCPU" ] && limitCPU=$requestCPU[ -z "$limitMemory" ] && limitMemory=$requestMemory  cDir=$(cd $(dirname .);pwd)[ -z "$outFile" ] && outputFile=$cDir/deployment.yaml[ -z "$templateFile" ] &&  templateFile=$cDir/deployment.tpl sed "s#%%work.name%%#$name#g; s#%%work.env%%#$env#g;s/%%work.replicaCount%%/$replicaCount/g;s#%%work.image.repository%%#$image#g;s/%%work.image.version%%/$version/g;s/%%work.limit.cpu%%/$limitCpu/g;s/%%work.limit.memory%%/$limitMemory/g;s/%%work.request.cpu%%/$requestCpu/g;s/%%work.request.memory%%/$requestMemory/g;" $templateFile > $outputFile
--



--




```
