### ISSUE TITLE
动手Minikube 

### ISSUE THREAD

**Issue by wmenjoy** [wmenjoy/awesome-knowleges#22]
# 介绍

## 什么是MiniKube

在个人电脑上，运行单节点Kubenates集群的一个工具。

### Linux
``` bash
grep -E --color 'vmx\|svm' /proc/cpuinfo
```
### MacS
```bash

sysctl -a \| grep -E --color 'machdep.cpu.features\|VMX'

```

**Comment by wmenjoy** [comment]
# 安装
## 安装依赖
kubectl
### Hypervisor
1. [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
2. [Vmware Funsion)(https://www.vmware.com/products/fusion)
## 安装步骤
### 下载并安装
Linux:
```
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube
sudo mv minikube /usr/local/bin
```
Mac:
```
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64 \  && chmod +x minikubesudo mv minikube /usr/local/bin
```
### 验证安装
``` bash
export HTTP_PROXY=http://<proxy hostname:port>
export HTTPS_PROXY=https://<proxy hostname:port>
export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
### --vm-driver根据实际情况选择，mac下比较多的时virtualbox，vwwarefusion,
###可以通过minikube config set vm-driver virtualbox 来设置默认的vm-driver
## minikube config set memory 4096 可用以设置minikube 分配的内存
minikube start --vm-driver=virtualbox   --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'   --image-mirror-country=cn --registry-mirror=https://registry.docker-cn.com
 
 
 
## 如果使用自定以的非https的registy 需要添 --insecure-registy
#minikube start --vm-driver=virtualbox   --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'   --image-mirror-country=cn --registry-mirror=https://registry.docker-cn.com --docker-env HTTP_RPOXY=//192.168.50.181:10001 --docker-env HTTPS_PROXY=http://192.168.50.181:10001 --docker-env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24,192.168.126.0/24 --insecure-registry=192.168.126.0/24 --log_dir=tmp --cpus 4 --memory 8129
## 执行kubectl cluster-info
kubectl cluster-info
Kubernetes master is running at https://192.168.99.100:8443
KubeDNS is running at https://192.168.99.100:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
 
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
## pods
## 执行 kubectl get pods -A 
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-7f9c544f75-5c9mr           1/1     Running   1          16h
kube-system   coredns-7f9c544f75-jjtrz           1/1     Running   1          16h
kube-system   etcd-minikube                      1/1     Running   1          16h
kube-system   kube-apiserver-minikube            1/1     Running   1          16h
kube-system   kube-controller-manager-minikube   1/1     Running   1          16h
kube-system   kube-proxy-68xds                   1/1     Running   1          16h
kube-system   kube-scheduler-minikube            1/1     Running   1          16h
kube-system   storage-provisioner                1/1     Running   2          16h
```
### Minikube的config配置
config配置位于~/.kube/config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/xxxx/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/xxxx/.minikube/client.crt
    client-key: /Users/liujinliang/.minikube/client.key
```

**Comment by wmenjoy** [comment]
# Minikube的操作
```
# 停止， 重启就是先 stop，后start，如果有配置修改建议使用minikube delete
minikube stop
# 如果start的配置修改了，请一定要使用minikube delete
minikube delete
# 查看安装状态
minikube status
# 查看minikube 日志
minikube logs
# 使mac 本地可以服用minikube vm的dockerd
eval $(minikube docker-env)
# 暴露 service服务
minikube service xxx
# 使用Loadbalancer
minikube tunnel
```

**Comment by wmenjoy** [comment]
# Minikube 开发一个服务
## 书写一个deployment.yml
以nginx为例
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      release: stabel
  template:
    metadata:
      labels:
        app: myapp
        release: stabel
        env: test
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
```
然后执行命令
```
kubectl apply -f ./deployment.yml

```

## 暴露服务
写一个service.yml， 这里使用NodePort类型
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: default
spec:
  type: NodePort
  selector:
    app: myapp
    release: stabel
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
```
然后执行命令
```
kubectl apply -f ./deployment.yml
# minikube service 会使用默认浏览器打开，如果不想打开，请使用minikube service myapp  --url=false
minikube service myapp
```

**Comment by wmenjoy** [comment]
# 使用Ingress 暴露服务
Ingress 涉及到Ingress controller， ingress Resource， configMap,  认证四个步骤，这里简化，只考虑Ingress controller， ingress Resource
## 开启Ingress controller
### 开启addons插件
``` bash
minikube addons enable ingress
```
### 验证
```
minikube addons list
➜  test minikube addons list
|-----------------------------|----------|--------------|
|         ADDON NAME          | PROFILE  |    STATUS    |
|-----------------------------|----------|--------------|
| dashboard                   | minikube | enabled ✅   |
| default-storageclass        | minikube | enabled ✅   |
| efk                         | minikube | disabled     |
| freshpod                    | minikube | disabled     |
| gvisor                      | minikube | disabled     |
| helm-tiller                 | minikube | disabled     |
| ingress                     | minikube | enabled ✅   |
| ingress-dns                 | minikube | disabled     |
| istio                       | minikube | disabled     |
| istio-provisioner           | minikube | disabled     |
| logviewer                   | minikube | disabled     |
| metrics-server              | minikube | enabled ✅   |
| nvidia-driver-installer     | minikube | disabled     |
| nvidia-gpu-device-plugin    | minikube | disabled     |
| registry                    | minikube | disabled     |
| registry-creds              | minikube | disabled     |
| storage-provisioner         | minikube | enabled ✅   |
| storage-provisioner-gluster | minikube | disabled     |
|-----------------------------|----------|--------------
```

## 部署两个服务
第一个服务选择nginx，yaml文件如下，执行 kubectl apply -f nginx.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: prod
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name:  nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
```
第二个服务为了简单，选择hello-app 直接执行

``` bash
kubectl run web --image=hansd/hello-app  --port=8080
kubectl expose deployment web--target-port=8080
```
检查
```
➜  test kubectl get pods
NAME                                READY   STATUS    RESTARTS   AGE
nginx-deployment-7485f4dd75-p64d7   1/1     Running   0          109m
web-84b88974b7-v25vm                1/1     Running   0          59m
➜  test kubectl get svc
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP   10.96.0.1       <none>        443/TCP          136m
nginx        ClusterIP   10.102.151.90   <none>        80/TCP           111m
web          NodePort    10.96.27.92     <none>        8080:30675/TCP   52m
```

## 添加Ingress Resource
### 创建ingress.yaml
``` yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello-world.info
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
      - path: /v2/*
        backend:
          serviceName: web
          servicePort: 8080
```
### 执行
```
kubectl apply -f ingress.yaml
```
### 添加域名，ip映射
``` zsh
# 获取ingress对外暴露的ip地址
➜  test kubectl get ingress
NAME            HOSTS              ADDRESS          PORTS   AGE
ingress-nginx   hello-world.info   192.168.99.105   80      80m
# 在/etc/hosts添加映射
xx.xxx.xx.xx hello-world.info
```
## 测试验证
```
  test curl hello-world.info/
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>
 
<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>
 
<p><em>Thank you for using nginx.</em></p>
</body>
</html>
➜  test curl hello-world.info/v2
Hello, world!Version: 1.0.0
Hostname: web-84b88974b7-v25vm
 
For hello-world.info /
```
